//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int id { get; set; }
        public int request_no { get; set; }
        public int volunteer_no { get; set; }
        public string collectiondate { get; set; }
        public string status { get; set; }
    }
}
